# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-20 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100, verbose_name='摘要'),
        ),
    ]
